//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVGLive.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hauptbahnhof")]
        public string Destination_1 {
            get {
                return ((string)(this["Destination_1"]));
            }
            set {
                this["Destination_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Karlsplatz")]
        public string Destination_2 {
            get {
                return ((string)(this["Destination_2"]));
            }
            set {
                this["Destination_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Marienplatz")]
        public string Destination_3 {
            get {
                return ((string)(this["Destination_3"]));
            }
            set {
                this["Destination_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ostbahnhof")]
        public string Destination_4 {
            get {
                return ((string)(this["Destination_4"]));
            }
            set {
                this["Destination_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int TableFontSize {
            get {
                return ((int)(this["TableFontSize"]));
            }
            set {
                this["TableFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TableType {
            get {
                return ((int)(this["TableType"]));
            }
            set {
                this["TableType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000342")]
        public string HeaderBackgroundColor {
            get {
                return ((string)(this["HeaderBackgroundColor"]));
            }
            set {
                this["HeaderBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00056C")]
        public string TableBackgroundColor1 {
            get {
                return ((string)(this["TableBackgroundColor1"]));
            }
            set {
                this["TableBackgroundColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF262A74")]
        public string TableBackgroundColor2 {
            get {
                return ((string)(this["TableBackgroundColor2"]));
            }
            set {
                this["TableBackgroundColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE8E8E8")]
        public string TableForegroundColor1 {
            get {
                return ((string)(this["TableForegroundColor1"]));
            }
            set {
                this["TableForegroundColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#55F1F1F1")]
        public string TableForegroundColor2 {
            get {
                return ((string)(this["TableForegroundColor2"]));
            }
            set {
                this["TableForegroundColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HeaderFontSize {
            get {
                return ((int)(this["HeaderFontSize"]));
            }
            set {
                this["HeaderFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99E8E8E8")]
        public string HeaderForegroundColor {
            get {
                return ((string)(this["HeaderForegroundColor"]));
            }
            set {
                this["HeaderForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int TimerRefreshInterval {
            get {
                return ((int)(this["TimerRefreshInterval"]));
            }
            set {
                this["TimerRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.3")]
        public float CaptionFontSizeCoeff {
            get {
                return ((float)(this["CaptionFontSizeCoeff"]));
            }
            set {
                this["CaptionFontSizeCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFEB85")]
        public string WarningForegroundColor {
            get {
                return ((string)(this["WarningForegroundColor"]));
            }
            set {
                this["WarningForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF4E48")]
        public string NoConnectionForegroundColor {
            get {
                return ((string)(this["NoConnectionForegroundColor"]));
            }
            set {
                this["NoConnectionForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE8E8E8")]
        public string CaptionForegroundColor {
            get {
                return ((string)(this["CaptionForegroundColor"]));
            }
            set {
                this["CaptionForegroundColor"] = value;
            }
        }
    }
}
